### ISSUE TITLE
Support annotations based service discovery of prom end points

### ISSUE THREAD

**Issue by vikramraman** [wavefrontHQ/wavefront-kubernetes-collector#2]
Basically add a separate discovery framework that auto discovers prom end points based on k8s pod annotations etc and auto configures prometheus sources accordingly.

**Comment by puckpuck** [comment]
`prometheus.io/scrape`: Scrape if this annotation is specified and set to "true"
`prometheus.io/path`: If the metrics path is not /metrics, define it with this annotation.
`prometheus.io/port`: Scrape the pod on the indicated port instead of the pod’s declared ports (default is a port-free target if none are declared).
`prometheus.io/scheme`: If the metrics scheme is not https, define it with this annotation.

**Comment by vikramraman** [comment]
This has now beed addressed: https://github.com/wavefrontHQ/wavefront-kubernetes-collector/pull/5
